=== Academic-Codex/SCC0661-Hipermidia-e-Multimidia/Schema2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="resumoescolar">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Identificacao">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Unidade" type="xs:string"/>
                            <xs:element name="Nome" type="xs:string"/>
                            <xs:element name="NUSP" type="xs:string"/>
                            <xs:element name="Ingresso" type="xs:date"/>
                            <xs:element name="Curso" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Semestre" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Disciplina" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Codigo">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="[A-Z]{3}[0-9]{4}"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Nome" type="xs:string"/>
                                        <xs:element name="Creditos" type="xs:integer"/>
                                        <xs:element name="Frequencia" minOccurs="0">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:integer">
                                                    <xs:minInclusive value="0"/>
                                                    <xs:maxInclusive value="100"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Nota" minOccurs="0">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:decimal">
                                                    <xs:minInclusive value="0"/>
                                                    <xs:maxInclusive value="10"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="Resultado">  
                                            <xs:simpleType>
                                                 <xs:restriction base="xs:string">
                                                     <xs:pattern value="A|RN|RF|RA|T|MA|I"/>
                                                 </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                             </xs:element>
                        </xs:sequence>
                        <xs:attribute name="ano" type="xs:integer" use="required"/>                        
                        <xs:attribute name="periodo" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="1|2"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
     </xs:element>
</xs:schema>

=== Academic-Codex/SCC0661-Hipermidia-e-Multimidia/Exemplo.xml
<?xml version="1.0" encoding="UTF-8"?>
<resumoescolar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema2.xsd">
    <Identificacao>
        <Unidade>EESC e ICMC</Unidade>
        <Nome>Leandro de Brito Leite</Nome>
        <NUSP>5656630</NUSP>
        <Ingresso>2006-02-16</Ingresso>
        <Curso>Engenharia da Computacao</Curso>
    </Identificacao>
    
    <Semestre ano="2006" periodo="1">
        <Disciplina>
            <Codigo>FCM0101</Codigo>
            <Nome>Fisica 1</Nome>
            <Creditos>6</Creditos>
            <Frequencia>100</Frequencia>
            <Nota>7.8</Nota>
            <Resultado>A</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>FFI0180</Codigo>
            <Nome>Laboratorio de Fisica Geral 1</Nome>
            <Creditos>2</Creditos>
            <Frequencia>83</Frequencia>
            <Nota>7.3</Nota>
            <Resultado>A</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SMA0301</Codigo>
            <Nome>Cálculo I</Nome>
            <Creditos>6</Creditos>
            <Frequencia>85</Frequencia>
            <Nota>2.0</Nota>
            <Resultado>RN</Resultado>
        </Disciplina>
    </Semestre>
    
    <Semestre ano="2006" periodo="2">
        <Disciplina>
            <Codigo>FCM0102</Codigo>
            <Nome>Física II</Nome>
            <Creditos>6</Creditos>
            <Frequencia>100</Frequencia>
            <Nota>6.0</Nota>
            <Resultado>A</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SCE0603</Codigo>
            <Nome>Algoritmos e Estruturas de Dados I</Nome>
            <Creditos>4</Creditos>
            <Frequencia>70</Frequencia>
            <Nota>6.1</Nota>
            <Resultado>A</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SMA0332</Codigo>
            <Nome>Cálculo II</Nome>
            <Creditos>6</Creditos>
            <Frequencia>100</Frequencia>
            <Nota>0.0</Nota>
            <Resultado>RN</Resultado>
        </Disciplina>
    </Semestre>
   
    <Semestre ano="2010" periodo="1">
        <Disciplina>
            <Codigo>SCC0630</Codigo>
            <Nome>Inteligência Artificial</Nome>            
            <Creditos>3</Creditos>
            <Frequencia>70</Frequencia>
            <Nota>6.6</Nota>
            <Resultado>A</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SEL0609</Codigo><Nome> Circuitos Eletrônicos I</Nome>
            
            <Creditos>4</Creditos>
            <Frequencia>90</Frequencia>
            <Nota>6.0</Nota>
            <Resultado>A</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SEL0610</Codigo><Nome> Laboratório de Circuitos Eletrônicos</Nome>
            
            <Creditos>2</Creditos>
            <Frequencia>100</Frequencia>
            <Nota>8.7</Nota>
            <Resultado>A</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SEL0611</Codigo><Nome> Fundamentos de Controle</Nome>
            
            <Creditos>4</Creditos>
            <Frequencia>87</Frequencia>
            <Nota>5.0</Nota>
            <Resultado>A</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SEL0615</Codigo>
            <Nome>Processamento Digital de Sinais</Nome>            
            <Creditos>2</Creditos>
            <Frequencia>80</Frequencia>
            <Nota>7.0</Nota>
            <Resultado>A</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SEL0629</Codigo>
            <Nome>Aplicações de Microprocessadores I</Nome>            
            <Creditos>3</Creditos>
            <Frequencia>93</Frequencia>
            <Nota>8.5</Nota>
            <Resultado>A</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SMA0301</Codigo>
            <Nome>Cálculo I</Nome>            
            <Creditos>6</Creditos>
            <Frequencia>88</Frequencia>
            <Nota>8.3</Nota>
            <Resultado>A</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SSC0611</Codigo>
            <Nome>Arquitetura de Computadores</Nome>            
            <Creditos>4</Creditos>
            <Frequencia>83</Frequencia>
            <Nota>6.7</Nota>
            <Resultado>A</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SSC0641</Codigo>
            <Nome>Redes de Computadores</Nome>            
            <Creditos>4</Creditos>
            <Frequencia>90</Frequencia>
            <Nota>6.7</Nota>
            <Resultado>A</Resultado>
        </Disciplina>
    </Semestre>
    
    <Semestre ano="2010" periodo="2">
        <Disciplina>
            <Codigo>SCC0661</Codigo>
            <Nome>Multimídia e Hipermídia</Nome>            
            <Creditos>3</Creditos>
            <Resultado>MA</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SEL0612</Codigo>
            <Nome>Ondas Eletromagnéticas</Nome>            
            <Creditos>4</Creditos>
            <Resultado>MA</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SEL0613</Codigo>
            <Nome>Circuitos Eletrônicos II</Nome>            
            <Creditos>4</Creditos>
            <Resultado>MA</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SEL0630</Codigo>
            <Nome>Aplicações de Microprocessadores II</Nome>            
            <Creditos>3</Creditos>
            <Resultado>MA</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SEL0635</Codigo>
            <Nome>Visão Computacional em Robótica</Nome>            
            <Creditos>2</Creditos>
            <Resultado>MA</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SEP0527</Codigo>
            <Nome>Gestão e Organização</Nome>            
            <Creditos>2</Creditos>
            <Resultado>MA</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SEP0587</Codigo>
            <Nome>Princípios de Economia</Nome>            
            <Creditos>2</Creditos>
            <Resultado>MA</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SME0141</Codigo>
            <Nome>Álgebra Linear e Equações Diferenciais</Nome>            
            <Creditos>4</Creditos>
            <Resultado>MA</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SME0601</Codigo>
            <Nome>Cálculo Numérico II</Nome>            
            <Creditos>2</Creditos>
            <Resultado>MA</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SME0645</Codigo>
            <Nome>Funções de Variável Complexa</Nome>            
            <Creditos>4</Creditos>
            <Resultado>MA</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SSC0570</Codigo>
            <Nome>Empreendedores em Informática</Nome>            
            <Creditos>4</Creditos>
            <Resultado>MA</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SSC0642</Codigo>
            <Nome>Sistemas Computacionais Distribuídos</Nome>            
            <Creditos>4</Creditos>
            <Resultado>MA</Resultado>
        </Disciplina>
    </Semestre>
    
    <Semestre ano="2011" periodo="1">
        <Disciplina>
            <Codigo>SCC0605</Codigo>
            <Nome>Teoria da Computação e Compiladores</Nome>
            <Creditos>4</Creditos>
            <Resultado>I</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SCC0650</Codigo>
            <Nome>Computação Gráfica</Nome>
            <Creditos>3</Creditos>
            <Resultado>I</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SEL0616</Codigo>
            <Nome>Princípios de Comunicação</Nome>
            <Creditos>3</Creditos>           
            <Resultado>I</Resultado></Disciplina>
        <Disciplina>
            <Codigo>SEL0617</Codigo>
            <Nome>Fundamentos de Microeletrônica</Nome>
            <Creditos>2</Creditos>
            <Resultado>I</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SEL0618</Codigo>
            <Nome>Projetos de Circuitos Integrados Analógicos</Nome>
            <Creditos>2</Creditos>
            <Resultado>I</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SMA0333</Codigo>
            <Nome>Cálculo III</Nome>
            <Creditos>4</Creditos>
            <Resultado>I</Resultado>
        </Disciplina>
        <Disciplina>
            <Codigo>SSC0621</Codigo>
            <Nome>Análise e Projeto Orientados a Objetos</Nome>
            <Creditos>3</Creditos>
            <Resultado>I</Resultado>
        </Disciplina>
    </Semestre>
    
</resumoescolar>
